return {
	["113"] = "☀️", -- Sunny / Clear
	["116"] = "🌤️", -- Partly Cloudy
	["119"] = "☁️", -- Cloudy
	["122"] = "☁️", -- Overcast
	["143"] = "🌫️", -- Mist
	["176"] = "🌦️", -- Patchy rain nearby / Light rain shower
	["179"] = "🌨️", -- Patchy snow nearby
	["182"] = "🌨️", -- Patchy sleet nearby
	["185"] = "🌨️", -- Patchy freezing drizzle nearby
	["200"] = "⛈️", -- Thundery outbreaks in nearby (using thunderstorm emoji)
	["227"] = "🌨️", -- Patchy light snow
	["230"] = "❄️", -- Heavy snow (using snowflake emoji)
	["248"] = "🌫️", -- Fog
	["260"] = "🌫️", -- Freezing Fog
	["263"] = "🌦️", -- Patchy light drizzle
	["266"] = "🌧️", -- Light drizzle
	["281"] = "🌧️", -- Freezing drizzle
	["284"] = "🌧️", -- Heavy freezing drizzle
	["293"] = "🌦️", -- Patchy light rain
	["296"] = "🌧️", -- Light rain
	["299"] = "🌧️", -- Moderate rain at times
	["302"] = "🌧️", -- Moderate rain
	["305"] = "🌧️", -- Heavy rain at times
	["308"] = "🌧️", -- Heavy rain
	["311"] = "🌧️", -- Light freezing rain
	["314"] = "🌧️", -- Moderate or Heavy freezing rain
	["317"] = "🌨️", -- Light sleet (using cloud with snow for sleet)
	["320"] = "🌨️", -- Moderate or Heavy sleet
	["323"] = "🌨️", -- Patchy light snow
	["326"] = "🌨️", -- Light snow
	["329"] = "🌨️", -- Patchy moderate snow
	["332"] = "❄️", -- Moderate snow
	["335"] = "❄️", -- Patchy heavy snow
	["338"] = "❄️", -- Heavy snow
	["350"] = "🌨️", -- Ice pellets (using cloud with snow)
	["353"] = "🌦️", -- Light rain shower
	["356"] = "🌧️", -- Moderate or heavy rain shower
	["359"] = "🌧️", -- Torrential rain shower
	["362"] = "🌨️", -- Light sleet showers
	["365"] = "🌨️", -- Moderate or heavy sleet showers
	["368"] = "🌨️", -- Light snow showers
	["371"] = "❄️", -- Moderate or heavy snow showers
	["374"] = "🌨️", -- Light showers of ice pellets
	["377"] = "🌨️", -- Moderate or heavy showers of ice pellets
	["386"] = "⛈️", -- Patchy light rain with thunder
	["389"] = "⛈️", -- Moderate or heavy rain with thunder
	["392"] = "⛈️", -- Patchy light snow with thunder
	["395"] = "⛈️", -- Moderate or heavy snow with thunder
	["default"] = "❓", -- Generic fallback icon
}
