use crate::ui::registry::Registry;
use gtk4::{self};

macro_rules! leafs { ($($t:ty),* $(,)?) => { $( Registry::register_leaf::<$t>(); )* }; }
macro_rules! containers { ($($t:ty),* $(,)?) => { $( Registry::register_container::<$t>(); )* }; }

pub fn init() {
    Registry::register_grid();

    containers!(
        gtk4::Window,
        gtk4::ApplicationWindow,
        gtk4::Dialog,
        gtk4::AboutDialog,
        gtk4::MessageDialog,
        gtk4::ColorChooserDialog,
        gtk4::FileChooserDialog,
        gtk4::FontChooserDialog,
        gtk4::AppChooserDialog,
        gtk4::Box,
        gtk4::CenterBox,
        gtk4::ListBox,
        gtk4::FlowBox,
        gtk4::Stack,
        gtk4::Overlay,
        gtk4::Paned,
        gtk4::Expander,
        gtk4::Revealer,
        gtk4::ScrolledWindow,
        gtk4::Viewport,
        gtk4::ActionBar,
        gtk4::HeaderBar,
        gtk4::Notebook,
        gtk4::Frame,
        gtk4::AspectFrame,
        gtk4::WindowHandle,
        gtk4::Popover,
        gtk4::Button,
        gtk4::ToggleButton,
        gtk4::LinkButton,
        gtk4::MenuButton,
        gtk4::CheckButton,
    );

    leafs!(
        gtk4::Label,
        gtk4::Image,
        gtk4::Picture,
        gtk4::Spinner,
        gtk4::ProgressBar,
        gtk4::LevelBar,
        gtk4::Calendar,
        gtk4::Video,
        gtk4::Separator,
        gtk4::Statusbar,
        gtk4::InfoBar,
        gtk4::Entry,
        gtk4::PasswordEntry,
        gtk4::SearchEntry,
        gtk4::SpinButton,
        gtk4::Switch,
        gtk4::Scale,
        gtk4::Range,
        gtk4::TextView,
        gtk4::ColorButton,
        gtk4::FontButton,
        gtk4::DropDown,
        gtk4::ComboBox,
        gtk4::ComboBoxText,
        gtk4::ListView,
        gtk4::GridView,
        gtk4::ColumnView,
        gtk4::DrawingArea,
        gtk4::GLArea,
        gtk4::EmojiChooser,
        gtk4::ShortcutsShortcut,
        gtk4::LockButton,
        gtk4::PopoverMenu,
        gtk4::PopoverMenuBar,
    );
}
